/**
 * Database Module
 *
 * PostgreSQL storage layer with connection pooling, migrations, and repositories.
 */

// Connection
export {
  createDatabase,
  createDatabaseFromEnv,
  type Database,
  type DatabaseConfig,
  type Sql,
} from './connection.js'

// Migrations
export {
  migrate,
  loadMigrations,
  getAppliedMigrations,
  getCurrentVersion,
  isSchemaUpToDate,
  getPendingMigrations,
  type Migration,
  type AppliedMigration,
  type MigrationResult,
} from './migrations.js'

// Repositories
export {
  // Context
  createRepositoryContext,
  type RepositoryContext,
  type PaginationOptions,
  type PaginatedResult,
  type Repository,
  // Raw Envelope
  createRawEnvelopeRepository,
  type RawEnvelopeRepository,
  // Canonical Entity
  createCanonicalEntityRepository,
  type CanonicalEntityRepository,
  type StoredEntity,
  type CanonicalEntityFilters,
  // Entity Source Mapping
  createEntitySourceMappingRepository,
  type EntitySourceMappingRepository,
  // Sync Job
  createSyncJobRepository,
  type SyncJobRepository,
  type SyncJob,
  type SyncJobInput,
  type SyncJobStatus,
  type SyncJobType,
  // Derived Job
  createDerivedJobRepository,
  type DerivedJobRepository,
  type DerivedJob,
  type DerivedJobInput,
  type DerivedJobStatus,
  // Account
  createAccountRepository,
  type AccountRepository,
  type Account,
  type AccountInput,
  type AccountCredentials,
  type AuthType,
  // Job Queue
  createJobQueueRepository,
  type JobQueueRepository,
  type QueueJob,
  type JobStatus,
  type EnqueueOptions,
  // Sync Task
  createSyncTaskRepository,
  type SyncTaskRepository,
  type SyncTask,
  type SyncTaskInput,
  type SyncType,
  type TaskMode,
  // Derived Task
  createDerivedTaskRepository,
  type DerivedTaskRepository,
  type DerivedTask,
  type DerivedTaskInput,
  type DerivedTaskMode,
  // Derived Run Log
  createDerivedRunLogRepository,
  type DerivedRunLogRepository,
  type DerivedRunLogRecord,
  type DerivedRunLogInput,
  type DerivedRunSampleInput,
  type DerivedRunStatus,
  // Conversational Memory
  createProjectsRepository,
  type ProjectsRepository,
  type ProjectRecord,
  type ProjectRow,
  type ProjectInput,
  type ProjectUpdateInput,
  type ProjectFilters,
  createGoalsRepository,
  type GoalsRepository,
  type GoalRecord,
  type GoalRow,
  type GoalInput,
  type GoalUpdateInput,
  type GoalFilters,
  createConversationDigestRepository,
  type ConversationDigestRepository,
  type ConversationDigestRecord,
  type ConversationDigestRow,
  type ConversationDigestInput,
  type ConversationDigestUpdateInput,
  createEntityMentionsRepository,
  type EntityMentionsRepository,
  type EntityMentionRecord,
  type EntityMentionRow,
  type EntityMentionInput,
  type EntityMentionFilters,
  type EntityMentionSimilarityOptions,
  // Transformations
  createTransformationRepository,
  type TransformationRepository,
  type TransformationRecord,
  type TransformationInput,
  // Evidence atoms
  createConfigFactsRepository,
  type ConfigFactsRepository,
  type ConfigFactRow,
  type ConfigFactInput,
  type ConfigType,
  type ValueType,
  createRuntimeFactsRepository,
  type RuntimeFactsRepository,
  type RuntimeFactRow,
  type RuntimeFactInput,
  type RuntimeFactType,
  createTestSpecsRepository,
  type TestSpecsRepository,
  type TestSpecRow,
  type TestSpecInput,
  type TestResult,
  createEvidenceRetrievalLogRepository,
  type EvidenceRetrievalLogRepository,
  type EvidenceRetrievalLogRow,
  type EvidenceRetrievalLogInput,
  type RetrievalStatus,
  // Agent Traces (cursor/agent-trace spec)
  createAgentTracesRepository,
  type AgentTracesRepository,
  type AgentTraceRow,
  type AgentTraceInput,
  type TraceFilterOptions,
  // Architecture boundaries
  createArchitectureRepository,
  type ArchitectureRepository,
  type ArchitectureRunStatus,
  type ArchitectureAlertSeverity,
  type ArchitectureAlertStatus,
  type ArchitectureRunRecord,
  type ArchitectureConcernRecord,
  type ArchitectureConcernFileRecord,
  type ArchitectureBoundaryRecord,
  type ArchitectureAlertRecord,
  type ArchitectureConcernDetail,
  type ArchitectureRunInput,
  type ArchitectureRunSuccessInput,
  type ArchitectureDataInput,
  type ArchitectureConcernsQuery,
  type ArchitectureBoundariesQuery,
  type ArchitectureAlertsQuery,
} from './repositories/index.js'
