import type { WorkItem } from '../wizard/work-item.js';
import { DEFAULT_WORK_BOUNDS } from '../wizard/work-item.js';
import type { AgentType } from '../agent/types.js';

/**
 * Declarative execution script generated by RuntimeScriptAgent.
 * Represents a DAG of WorkItems to execute.
 */
export interface RuntimeScript {
  /** The goal this script accomplishes */
  goal: string;
  /** Ordered list of work items (topologically sorted) */
  workItems: WorkItem[];
  /** System context gathered during exploration */
  systemContext: SystemContext;
  /** Timestamp of script creation */
  createdAt: number;
}

/**
 * System context gathered by ExplorerAgent.
 */
export interface SystemContext {
  /** Detected package managers (npm, pip, cargo, etc.) */
  packageManagers: string[];
  /** Detected frameworks (React, FastAPI, Express, etc.) */
  frameworks: string[];
  /** Detected languages (TypeScript, Python, Rust, etc.) */
  languages: string[];
  /** Operating system */
  os: string;
  /** Relevant artifacts/files discovered */
  artifacts: Artifact[];
  /** Codebase patterns/conventions */
  patterns: string[];
}

/**
 * An artifact discovered during exploration.
 */
export interface Artifact {
  /** File path */
  path: string;
  /** Type of artifact */
  type: 'config' | 'source' | 'test' | 'doc' | 'other';
  /** Brief description */
  description?: string;
  /** Relevance to the goal (0-1) */
  relevance?: number;
}

/**
 * Raw output format from RuntimeScriptAgent.
 * Parsed into RuntimeScript.
 */
export interface RuntimeScriptOutput {
  goal: string;
  workItems: Array<{
    id: string;
    objective: string;
    delta: string;
    agent: AgentType;
    dependencies: string[];
    toolHint?: string;
    targetPaths?: string[];
    params?: Record<string, unknown>;
  }>;
}

/**
 * Parse RuntimeScriptAgent output into RuntimeScript.
 */
export function parseRuntimeScript(
  output: RuntimeScriptOutput,
  systemContext: SystemContext
): RuntimeScript {
  const workItems: WorkItem[] = output.workItems.map((item) => ({
    workId: item.id,
    goal: output.goal,
    objective: item.objective,
    delta: item.delta,
    dependencies: Object.freeze(item.dependencies),
    agent: item.agent,
    bounds: DEFAULT_WORK_BOUNDS,
    toolHint: item.toolHint,
    targetPaths: item.targetPaths ? Object.freeze(item.targetPaths) : undefined,
    params: item.params,
  }));

  return {
    goal: output.goal,
    workItems,
    systemContext,
    createdAt: Date.now(),
  };
}
