/**
 * Design Specification Types
 *
 * Types for UI design extraction and project scaffolding.
 * Used by the /design-fork skill.
 */

// ============================================
// COLOR & TYPOGRAPHY
// ============================================

/**
 * Color palette extracted from design or preset.
 */
export interface ColorPalette {
  id: string;
  name: string;
  primary: string;
  secondary: string;
  background: string;
  surface: string;
  text: string;
  textMuted?: string;
  accent?: string;
  success?: string;
  warning?: string;
  error?: string;
}

/**
 * Typography specification.
 */
export interface TypographySpec {
  id: string;
  headings: string;
  body: string;
  mono: string;
}

/**
 * Full typography with sizes.
 */
export interface TypographyFull {
  headings: { family: string; weight: number };
  body: { family: string; weight: number };
  sizes: {
    h1: string;
    h2: string;
    h3?: string;
    body: string;
    small: string;
  };
}

/**
 * Spacing scale configuration.
 */
export interface SpacingScale {
  unit: number;
  containerPadding: number;
  cardPadding: number;
  gap: number;
}

// ============================================
// AESTHETIC PRESETS
// ============================================

/**
 * Aesthetic preset for design generation.
 */
export interface AestheticPreset {
  id: string;
  name: string;
  description: string;
  modifiers: string[];
  temperature: number;
}

// ============================================
// LAYOUT & COMPONENTS
// ============================================

/**
 * Layout types supported by the design system.
 */
export type LayoutType =
  | 'sidebar-main'
  | 'top-nav-main'
  | 'full-width'
  | 'split'
  | 'dashboard-grid';

/**
 * Layout region definition.
 */
export interface LayoutRegion {
  id: string;
  position: 'top' | 'left' | 'right' | 'bottom' | 'center';
  size: string;
  components: string[];
}

/**
 * Component specification extracted from design.
 */
export interface ComponentSpec {
  id: string;
  type: string;
  region: string;
  props: Record<string, unknown>;
  variants?: string[];
  interactions?: string[];
}

/**
 * Page specification.
 */
export interface PageSpec {
  id: string;
  route: string;
  title: string;
  layout: string;
  sections: string[];
  components: string[];
}

/**
 * State flow for interactive components.
 */
export interface StateFlow {
  id: string;
  trigger: string;
  states: string[];
  affectsComponents: string[];
}

// ============================================
// DESIGN SPEC (FULL)
// ============================================

/**
 * Complete design specification.
 * Generated by vision analysis of selected design image.
 */
export interface DesignSpec {
  meta: {
    id: string;
    name: string;
    description: string;
    sourceImage: string;
    createdAt: string;
    aesthetic: string;
  };

  layout: {
    type: LayoutType;
    regions: LayoutRegion[];
  };

  components: ComponentSpec[];

  theme: {
    colors: ColorPalette;
    typography: TypographyFull;
    spacing: SpacingScale;
    borderRadius: string;
    shadows: Record<string, string>;
  };

  pages: PageSpec[];

  stateFlows: StateFlow[];

  scaffold: {
    framework: 'react' | 'vue' | 'svelte';
    styling: 'tailwind' | 'css-modules' | 'styled-components';
    stateManagement: 'zustand' | 'redux' | 'context' | 'none';
  };
}

// ============================================
// IMAGE GENERATION
// ============================================

/**
 * Parameters for image generation.
 */
export interface ImageGenParams {
  prompt: string;
  width?: number;
  height?: number;
  seed?: number;
}

/**
 * Result of image generation.
 */
export interface ImageGenResult {
  url: string;
  localPath: string;
  seed: number;
  aesthetic: string;
  index: number;
}

/**
 * Design prompt parameters.
 */
export interface DesignPromptParams {
  userRequest: string;
  aesthetic: AestheticPreset;
  colorPalette: ColorPalette;
  typography: TypographySpec;
  layoutHints: string[];
}

// ============================================
// GALLERY & SELECTION
// ============================================

/**
 * Gallery image entry.
 */
export interface GalleryImage {
  path: string;
  label: string;
  aesthetic: string;
  metadata: {
    seed: number;
    width: number;
    height: number;
    generatedAt: string;
  };
}

/**
 * User selection result.
 */
export interface SelectionResult {
  indices: number[];
  images: GalleryImage[];
}

// ============================================
// SCAFFOLD CONFIG
// ============================================

/**
 * Project scaffold configuration.
 */
export interface ScaffoldConfig {
  projectName: string;
  outputDir: string;
  designSpec: DesignSpec;
  referenceImage: string;
  includeStubs: boolean;
}

/**
 * Generated file info.
 */
export interface GeneratedFile {
  path: string;
  type: 'config' | 'component' | 'style' | 'page' | 'layout' | 'asset';
  content?: string;
}

/**
 * Scaffold result.
 */
export interface ScaffoldResult {
  projectPath: string;
  files: GeneratedFile[];
  nextSteps: string[];
}
