import { computeSessionInsights, type AgentRequest, type Session } from './models';

const iso = (msAgo: number) => new Date(Date.now() - msAgo).toISOString();

function sess(partial: Omit<Session, 'insights' | 'watcherDecisions'> & { watcherDecisions?: Session['watcherDecisions'] }): Session {
  return { ...partial, watcherDecisions: partial.watcherDecisions ?? [], insights: computeSessionInsights({ ...partial, watcherDecisions: partial.watcherDecisions ?? [] }) };
}

// ============================================
// MOCK AGENT REQUESTS
// ============================================

const runningRequest: AgentRequest = {
  id: 'task-001',
  sessionId: 'S-1042',
  state: 'running',
  userInput: 'Refactor the authentication module to use JWT tokens',
  createdAt: iso(1000 * 60 * 5),
  startedAt: iso(1000 * 60 * 4),
  workItemsCompleted: 3,
  workItemsTotal: 5,
  totalToolCalls: 6,
  plan: {
    goal: 'Refactor authentication to JWT',
    workItems: [
      {
        workId: 'w1',
        goal: 'Refactor authentication to JWT',
        objective: 'Read current auth implementation',
        dependencies: [],
        agent: 'explorer',
        status: 'completed',
        toolHint: 'Read',
        durationMs: 450,
      },
      {
        workId: 'w2',
        goal: 'Refactor authentication to JWT',
        objective: 'Identify patterns and dependencies',
        dependencies: ['w1'],
        agent: 'explorer',
        status: 'completed',
        durationMs: 1200,
      },
      {
        workId: 'w3',
        goal: 'Refactor authentication to JWT',
        objective: 'Update AuthService with JWT signing',
        dependencies: ['w2'],
        agent: 'standard',
        status: 'in_progress',
        toolHint: 'Edit',
      },
      {
        workId: 'w4',
        goal: 'Refactor authentication to JWT',
        objective: 'Add token validation middleware',
        dependencies: ['w3'],
        agent: 'standard',
        status: 'pending',
        toolHint: 'Edit',
      },
      {
        workId: 'w5',
        goal: 'Refactor authentication to JWT',
        objective: 'Verify changes compile and tests pass',
        dependencies: ['w4'],
        agent: 'tester',
        status: 'pending',
        toolHint: 'Bash',
      },
    ],
    systemContext: {
      packageManagers: ['npm'],
      frameworks: ['express'],
      languages: ['typescript'],
      os: 'darwin',
      artifacts: [],
      patterns: ['jwt-auth'],
    },
    createdAt: iso(1000 * 60 * 4),
  },
  toolCalls: [
    {
      id: 'tc-1',
      toolName: 'Read',
      arguments: { cwd: '/repo', path: 'src/auth/service.ts' },
      result: '234 lines',
      success: true,
      durationMs: 120,
      timestamp: iso(1000 * 60 * 4),
    },
    {
      id: 'tc-2',
      toolName: 'Read',
      arguments: { cwd: '/repo', path: 'src/auth/middleware.ts' },
      result: '89 lines',
      success: true,
      durationMs: 85,
      timestamp: iso(1000 * 60 * 3.5),
    },
    {
      id: 'tc-3',
      toolName: 'Grep',
      arguments: { cwd: '/repo', pattern: 'session.*token', path: 'src/' },
      result: '12 matches in 4 files',
      success: true,
      durationMs: 340,
      timestamp: iso(1000 * 60 * 3),
    },
    {
      id: 'tc-4',
      toolName: 'Write',
      arguments: { cwd: '/repo', path: 'src/auth/jwt.ts', content: '...' },
      result: 'Created new file',
      success: true,
      durationMs: 95,
      timestamp: iso(1000 * 60 * 2.5),
    },
    {
      id: 'tc-5',
      toolName: 'Edit',
      arguments: { cwd: '/repo', path: 'src/auth/service.ts', content: '...' },
      result: 'Updated 45 lines',
      success: true,
      durationMs: 110,
      timestamp: iso(1000 * 60 * 2),
    },
    {
      id: 'tc-6',
      toolName: 'Read',
      arguments: { cwd: '/repo', path: 'src/auth/types.ts' },
      result: '56 lines',
      success: true,
      durationMs: 78,
      timestamp: iso(1000 * 60 * 1.5),
    },
  ],
  llmCalls: [],
  userPrompts: [],
  contextWindow: {
    inputTokens: 42000,
    peakInputTokens: 42000,
    outputTokens: 1200,
    totalOutputTokens: 6200,
    maxTokens: 200000,
    percentageUsed: 0.21,
    messageCount: 18,
    timestamp: iso(1000 * 60 * 1),
  },
};

const successRequest: AgentRequest = {
  id: 'task-002',
  sessionId: 'S-1042',
  state: 'success',
  userInput: 'Fix the login validation bug where empty passwords pass',
  createdAt: iso(1000 * 60 * 20),
  startedAt: iso(1000 * 60 * 19),
  endedAt: iso(1000 * 60 * 15),
  workItemsCompleted: 4,
  workItemsTotal: 4,
  totalToolCalls: 5,
  durationMs: 4 * 60 * 1000,
  plan: {
    goal: 'Fix empty password validation bug',
    workItems: [
      {
        workId: 'w1',
        goal: 'Fix empty password validation bug',
        objective: 'Locate login validation logic',
        dependencies: [],
        agent: 'explorer',
        status: 'completed',
        toolHint: 'Grep',
        durationMs: 280,
      },
      {
        workId: 'w2',
        goal: 'Fix empty password validation bug',
        objective: 'Read validation function',
        dependencies: ['w1'],
        agent: 'explorer',
        status: 'completed',
        toolHint: 'Read',
        durationMs: 150,
      },
      {
        workId: 'w3',
        goal: 'Fix empty password validation bug',
        objective: 'Add empty string check before hash comparison',
        dependencies: ['w2'],
        agent: 'standard',
        status: 'completed',
        toolHint: 'Edit',
        durationMs: 420,
      },
      {
        workId: 'w4',
        goal: 'Fix empty password validation bug',
        objective: 'Run existing tests to verify fix',
        dependencies: ['w3'],
        agent: 'tester',
        status: 'completed',
        toolHint: 'Bash',
        durationMs: 3200,
      },
    ],
    systemContext: {
      packageManagers: ['npm'],
      frameworks: ['express'],
      languages: ['typescript'],
      os: 'darwin',
      artifacts: [],
      patterns: [],
    },
    createdAt: iso(1000 * 60 * 19),
  },
  toolCalls: [
    {
      id: 'tc-s1',
      toolName: 'Grep',
      arguments: { cwd: '/repo', pattern: 'validatePassword', path: 'src/' },
      result: '3 matches in 2 files',
      success: true,
      durationMs: 180,
      timestamp: iso(1000 * 60 * 19),
    },
    {
      id: 'tc-s2',
      toolName: 'Read',
      arguments: { cwd: '/repo', path: 'src/auth/validation.ts' },
      result: '78 lines',
      success: true,
      durationMs: 95,
      timestamp: iso(1000 * 60 * 18.5),
    },
    {
      id: 'tc-s3',
      toolName: 'Edit',
      arguments: { cwd: '/repo', path: 'src/auth/validation.ts', content: '...' },
      result: 'Updated validatePassword function',
      success: true,
      durationMs: 120,
      timestamp: iso(1000 * 60 * 17),
    },
    {
      id: 'tc-s4',
      toolName: 'Bash',
      arguments: { cwd: '/repo', command: 'npm test -- --grep "password"' },
      result: '8 tests passed',
      success: true,
      durationMs: 2800,
      timestamp: iso(1000 * 60 * 16),
    },
    {
      id: 'tc-s5',
      toolName: 'Bash',
      arguments: { cwd: '/repo', command: 'npm run lint' },
      result: 'No issues found',
      success: true,
      durationMs: 450,
      timestamp: iso(1000 * 60 * 15.5),
    },
  ],
  reflection: {
    verdict: 'accept',
    confidence: 0.92,
    qualityScore: 0.88,
    reasoning: 'Fix is minimal and targeted. Tests pass. Added early return for empty strings before expensive hash comparison.',
    issues: [],
  },
  llmCalls: [],
  userPrompts: [],
  contextWindow: {
    inputTokens: 68000,
    peakInputTokens: 68000,
    outputTokens: 1800,
    totalOutputTokens: 8200,
    maxTokens: 200000,
    percentageUsed: 0.34,
    messageCount: 24,
    timestamp: iso(1000 * 60 * 15),
  },
};

const errorRequest: AgentRequest = {
  id: 'task-003',
  sessionId: 'S-1042',
  state: 'error',
  userInput: 'Deploy the application to production',
  createdAt: iso(1000 * 60 * 35),
  startedAt: iso(1000 * 60 * 34),
  endedAt: iso(1000 * 60 * 32),
  workItemsCompleted: 2,
  workItemsTotal: 4,
  totalToolCalls: 4,
  durationMs: 2 * 60 * 1000,
  errorMessage: 'DEPLOYMENT_FAILED: Missing required environment variable STRIPE_API_KEY',
  plan: {
    goal: 'Deploy application to production',
    workItems: [
      {
        workId: 'w1',
        goal: 'Deploy application to production',
        objective: 'Run production build',
        dependencies: [],
        agent: 'standard',
        status: 'completed',
        toolHint: 'Bash',
        durationMs: 45000,
      },
      {
        workId: 'w2',
        goal: 'Deploy application to production',
        objective: 'Run pre-deploy checks',
        dependencies: ['w1'],
        agent: 'tester',
        status: 'completed',
        toolHint: 'Bash',
        durationMs: 8000,
      },
      {
        workId: 'w3',
        goal: 'Deploy application to production',
        objective: 'Deploy to production environment',
        dependencies: ['w2'],
        agent: 'standard',
        status: 'failed',
        toolHint: 'Bash',
        error: 'Missing STRIPE_API_KEY environment variable',
      },
      {
        workId: 'w4',
        goal: 'Deploy application to production',
        objective: 'Verify deployment health',
        dependencies: ['w3'],
        agent: 'standard',
        status: 'skipped',
        toolHint: 'Bash',
      },
    ],
    systemContext: {
      packageManagers: ['npm'],
      frameworks: ['express'],
      languages: ['typescript'],
      os: 'linux',
      artifacts: [],
      patterns: [],
    },
    createdAt: iso(1000 * 60 * 34),
  },
  toolCalls: [
    {
      id: 'tc-e1',
      toolName: 'Bash',
      arguments: { cwd: '/repo', command: 'npm run build:prod' },
      result: 'Build completed in 42s',
      success: true,
      durationMs: 42000,
      timestamp: iso(1000 * 60 * 34),
    },
    {
      id: 'tc-e2',
      toolName: 'Bash',
      arguments: { cwd: '/repo', command: 'npm run test:integration' },
      result: '24 tests passed',
      success: true,
      durationMs: 8000,
      timestamp: iso(1000 * 60 * 33.5),
    },
    {
      id: 'tc-e3',
      toolName: 'Bash',
      arguments: { cwd: '/repo', command: 'npm run deploy:prod' },
      result: 'Error: STRIPE_API_KEY is not set',
      success: false,
      durationMs: 1200,
      timestamp: iso(1000 * 60 * 33),
    },
    {
      id: 'tc-e4',
      toolName: 'Read',
      arguments: { cwd: '/repo', path: '.env.production' },
      result: 'File not found',
      success: false,
      durationMs: 45,
      timestamp: iso(1000 * 60 * 32.5),
    },
  ],
  reflection: {
    verdict: 'abort_goal',
    confidence: 0.95,
    qualityScore: 0.0,
    reasoning: 'Cannot proceed without required secrets. User must configure STRIPE_API_KEY in environment.',
    issues: ['Missing STRIPE_API_KEY', 'No .env.production file found'],
  },
  llmCalls: [],
  userPrompts: [],
  contextWindow: {
    inputTokens: 140000,
    peakInputTokens: 145000,
    outputTokens: 2400,
    totalOutputTokens: 13400,
    maxTokens: 200000,
    percentageUsed: 0.70,
    messageCount: 32,
    timestamp: iso(1000 * 60 * 32),
  },
};

const queuedRequest: AgentRequest = {
  id: 'task-004',
  sessionId: 'S-1043',
  state: 'queued',
  userInput: 'Add unit tests for the user profile component',
  createdAt: iso(1000 * 60 * 2),
  workItemsCompleted: 0,
  workItemsTotal: 0,
  totalToolCalls: 0,
  toolCalls: [],
  llmCalls: [],
  userPrompts: [],
};

// ============================================
// MOCK SESSIONS WITH REQUESTS
// ============================================

export const mockSessions: Session[] = [
  sess({
    id: 'S-1042',
    userId: 'user_81b2',
    state: 'active',
    env: 'prod',
    createdAt: iso(1000 * 60 * 40),
    startedAt: iso(1000 * 60 * 34),
    tags: ['voice', 'project-alpha'],
    meta: {
      clientType: 'voice',
      workingDir: '/home/dev/project-alpha',
    },
    requests: [runningRequest, successRequest, errorRequest],
  }),
  sess({
    id: 'S-1043',
    userId: 'user_1f0a',
    state: 'idle',
    env: 'dev',
    createdAt: iso(1000 * 60 * 15),
    startedAt: iso(1000 * 60 * 12),
    tags: ['tui', 'sandbox'],
    meta: {
      clientType: 'tui',
      workingDir: '/home/dev/sandbox',
    },
    requests: [queuedRequest],
  }),
  sess({
    id: 'S-1044',
    userId: 'user_3x7p',
    state: 'ended',
    env: 'staging',
    createdAt: iso(1000 * 60 * 60),
    startedAt: iso(1000 * 60 * 55),
    endedAt: iso(1000 * 60 * 45),
    tags: ['api', 'ci-pipeline'],
    meta: {
      clientType: 'api',
      workingDir: '/builds/ci-runner/workspace',
    },
    requests: [
      {
        id: 'task-005',
        sessionId: 'S-1044',
        state: 'success',
        userInput: 'Run the full test suite and report coverage',
        createdAt: iso(1000 * 60 * 55),
        startedAt: iso(1000 * 60 * 54),
        endedAt: iso(1000 * 60 * 46),
        workItemsCompleted: 3,
        workItemsTotal: 3,
        totalToolCalls: 4,
        durationMs: 8 * 60 * 1000,
        plan: {
          goal: 'Execute full test suite with coverage',
          workItems: [
            { workId: 'w1', goal: 'Execute test suite', objective: 'Install dependencies', dependencies: [], agent: 'standard', status: 'completed', durationMs: 12000 },
            { workId: 'w2', goal: 'Execute test suite', objective: 'Run pytest with coverage', dependencies: ['w1'], agent: 'tester', status: 'completed', toolHint: 'Bash', durationMs: 180000 },
            { workId: 'w3', goal: 'Execute test suite', objective: 'Generate coverage report', dependencies: ['w2'], agent: 'standard', status: 'completed', durationMs: 5000 },
          ],
          systemContext: {
            packageManagers: ['pip'],
            frameworks: ['pytest'],
            languages: ['python'],
            os: 'linux',
            artifacts: [],
            patterns: [],
          },
          createdAt: iso(1000 * 60 * 54),
        },
        toolCalls: [
          { id: 'tc-ci1', toolName: 'Bash', arguments: { cwd: '/repo', command: 'pip install -e .[dev]' }, result: 'Installed 45 packages', success: true, durationMs: 11500, timestamp: iso(1000 * 60 * 54) },
          { id: 'tc-ci2', toolName: 'Bash', arguments: { cwd: '/repo', command: 'pytest --cov=src' }, result: '156 tests, 94% coverage', success: true, durationMs: 178000, timestamp: iso(1000 * 60 * 52) },
          { id: 'tc-ci3', toolName: 'Bash', arguments: { cwd: '/repo', command: 'coverage html' }, result: 'HTML report generated', success: true, durationMs: 4800, timestamp: iso(1000 * 60 * 47) },
          { id: 'tc-ci4', toolName: 'Read', arguments: { cwd: '/repo', path: 'coverage/index.html' }, result: '2.4KB', success: true, durationMs: 45, timestamp: iso(1000 * 60 * 46.5) },
        ],
        reflection: {
          verdict: 'accept',
          confidence: 0.98,
          qualityScore: 0.94,
          reasoning: 'All 156 tests passed. Coverage at 94% exceeds threshold. Report generated successfully.',
          issues: [],
        },
        llmCalls: [],
        userPrompts: [],
      },
    ],
  }),
];
