import { computeSessionInsights, type AgentRequest, type Session } from './models';

const iso = (msAgo: number) => new Date(Date.now() - msAgo).toISOString();

function sess(partial: Omit<Session, 'insights'>): Session {
  return { ...partial, insights: computeSessionInsights(partial) };
}

// ============================================
// MOCK AGENT REQUESTS
// ============================================

const runningRequest: AgentRequest = {
  id: 'task-001',
  sessionId: 'S-1042',
  state: 'running',
  userInput: 'Refactor the authentication module to use JWT tokens',
  createdAt: iso(1000 * 60 * 5),
  startedAt: iso(1000 * 60 * 4),
  stepsCompleted: 3,
  stepsTotal: 5,
  totalToolCalls: 6,
  plan: {
    goal: 'Refactor authentication to JWT',
    steps: [
      {
        stepNum: 1,
        objective: 'Read current auth implementation',
        status: 'completed',
        phase: 'discovery',
        toolHint: 'Read',
        required: true,
        durationMs: 450,
      },
      {
        stepNum: 2,
        objective: 'Identify patterns and dependencies',
        status: 'completed',
        phase: 'discovery',
        required: true,
        durationMs: 1200,
      },
      {
        stepNum: 3,
        objective: 'Update AuthService with JWT signing',
        status: 'in_progress',
        phase: 'execution',
        toolHint: 'Edit',
        required: true,
      },
      {
        stepNum: 4,
        objective: 'Add token validation middleware',
        status: 'pending',
        phase: 'execution',
        toolHint: 'Edit',
        required: true,
      },
      {
        stepNum: 5,
        objective: 'Verify changes compile and tests pass',
        status: 'pending',
        phase: 'execution',
        toolHint: 'Bash',
        required: false,
      },
    ],
  },
  toolCalls: [
    {
      id: 'tc-1',
      toolName: 'Read',
      arguments: { cwd: '/repo', path: 'src/auth/service.ts' },
      result: '234 lines',
      success: true,
      durationMs: 120,
      timestamp: iso(1000 * 60 * 4),
    },
    {
      id: 'tc-2',
      toolName: 'Read',
      arguments: { cwd: '/repo', path: 'src/auth/middleware.ts' },
      result: '89 lines',
      success: true,
      durationMs: 85,
      timestamp: iso(1000 * 60 * 3.5),
    },
    {
      id: 'tc-3',
      toolName: 'Grep',
      arguments: { cwd: '/repo', pattern: 'session.*token', path: 'src/' },
      result: '12 matches in 4 files',
      success: true,
      durationMs: 340,
      timestamp: iso(1000 * 60 * 3),
    },
    {
      id: 'tc-4',
      toolName: 'Write',
      arguments: { cwd: '/repo', path: 'src/auth/jwt.ts', content: '...' },
      result: 'Created new file',
      success: true,
      durationMs: 95,
      timestamp: iso(1000 * 60 * 2.5),
    },
    {
      id: 'tc-5',
      toolName: 'Edit',
      arguments: { cwd: '/repo', path: 'src/auth/service.ts', content: '...' },
      result: 'Updated 45 lines',
      success: true,
      durationMs: 110,
      timestamp: iso(1000 * 60 * 2),
    },
    {
      id: 'tc-6',
      toolName: 'Read',
      arguments: { cwd: '/repo', path: 'src/auth/types.ts' },
      result: '56 lines',
      success: true,
      durationMs: 78,
      timestamp: iso(1000 * 60 * 1.5),
    },
  ],
  llmCalls: [],
  planSnapshots: [],
  userPrompts: [],
  contextWindow: {
    contextTokens: 42000,
    outputTokens: 6200,
    totalTokens: 48200,
    maxTokens: 200000,
    percentageUsed: 0.21,
    messageCount: 18,
    timestamp: iso(1000 * 60 * 1),
  },
};

const successRequest: AgentRequest = {
  id: 'task-002',
  sessionId: 'S-1042',
  state: 'success',
  userInput: 'Fix the login validation bug where empty passwords pass',
  createdAt: iso(1000 * 60 * 20),
  startedAt: iso(1000 * 60 * 19),
  endedAt: iso(1000 * 60 * 15),
  stepsCompleted: 4,
  stepsTotal: 4,
  totalToolCalls: 5,
  durationMs: 4 * 60 * 1000,
  plan: {
    goal: 'Fix empty password validation bug',
    steps: [
      {
        stepNum: 1,
        objective: 'Locate login validation logic',
        status: 'completed',
        phase: 'discovery',
        toolHint: 'Grep',
        required: true,
        durationMs: 280,
      },
      {
        stepNum: 2,
        objective: 'Read validation function',
        status: 'completed',
        phase: 'discovery',
        toolHint: 'Read',
        required: true,
        durationMs: 150,
      },
      {
        stepNum: 3,
        objective: 'Add empty string check before hash comparison',
        status: 'completed',
        phase: 'execution',
        toolHint: 'Edit',
        required: true,
        durationMs: 420,
      },
      {
        stepNum: 4,
        objective: 'Run existing tests to verify fix',
        status: 'completed',
        phase: 'execution',
        toolHint: 'Bash',
        required: true,
        durationMs: 3200,
      },
    ],
  },
  toolCalls: [
    {
      id: 'tc-s1',
      toolName: 'Grep',
      arguments: { cwd: '/repo', pattern: 'validatePassword', path: 'src/' },
      result: '3 matches in 2 files',
      success: true,
      durationMs: 180,
      timestamp: iso(1000 * 60 * 19),
    },
    {
      id: 'tc-s2',
      toolName: 'Read',
      arguments: { cwd: '/repo', path: 'src/auth/validation.ts' },
      result: '78 lines',
      success: true,
      durationMs: 95,
      timestamp: iso(1000 * 60 * 18.5),
    },
    {
      id: 'tc-s3',
      toolName: 'Edit',
      arguments: { cwd: '/repo', path: 'src/auth/validation.ts', content: '...' },
      result: 'Updated validatePassword function',
      success: true,
      durationMs: 120,
      timestamp: iso(1000 * 60 * 17),
    },
    {
      id: 'tc-s4',
      toolName: 'Bash',
      arguments: { cwd: '/repo', command: 'npm test -- --grep "password"' },
      result: '8 tests passed',
      success: true,
      durationMs: 2800,
      timestamp: iso(1000 * 60 * 16),
    },
    {
      id: 'tc-s5',
      toolName: 'Bash',
      arguments: { cwd: '/repo', command: 'npm run lint' },
      result: 'No issues found',
      success: true,
      durationMs: 450,
      timestamp: iso(1000 * 60 * 15.5),
    },
  ],
  reflection: {
    verdict: 'accept',
    confidence: 0.92,
    qualityScore: 0.88,
    reasoning: 'Fix is minimal and targeted. Tests pass. Added early return for empty strings before expensive hash comparison.',
    issues: [],
  },
  llmCalls: [],
  planSnapshots: [],
  userPrompts: [],
  contextWindow: {
    contextTokens: 68000,
    outputTokens: 8200,
    totalTokens: 76200,
    maxTokens: 200000,
    percentageUsed: 0.34,
    messageCount: 24,
    timestamp: iso(1000 * 60 * 15),
  },
};

const errorRequest: AgentRequest = {
  id: 'task-003',
  sessionId: 'S-1042',
  state: 'error',
  userInput: 'Deploy the application to production',
  createdAt: iso(1000 * 60 * 35),
  startedAt: iso(1000 * 60 * 34),
  endedAt: iso(1000 * 60 * 32),
  stepsCompleted: 2,
  stepsTotal: 4,
  totalToolCalls: 4,
  durationMs: 2 * 60 * 1000,
  errorMessage: 'DEPLOYMENT_FAILED: Missing required environment variable STRIPE_API_KEY',
  plan: {
    goal: 'Deploy application to production',
    steps: [
      {
        stepNum: 1,
        objective: 'Run production build',
        status: 'completed',
        phase: 'execution',
        toolHint: 'Bash',
        required: true,
        durationMs: 45000,
      },
      {
        stepNum: 2,
        objective: 'Run pre-deploy checks',
        status: 'completed',
        phase: 'execution',
        toolHint: 'Bash',
        required: true,
        durationMs: 8000,
      },
      {
        stepNum: 3,
        objective: 'Deploy to production environment',
        status: 'failed',
        phase: 'execution',
        toolHint: 'Bash',
        required: true,
        error: 'Missing STRIPE_API_KEY environment variable',
      },
      {
        stepNum: 4,
        objective: 'Verify deployment health',
        status: 'skipped',
        phase: 'execution',
        toolHint: 'Bash',
        required: false,
      },
    ],
  },
  toolCalls: [
    {
      id: 'tc-e1',
      toolName: 'Bash',
      arguments: { cwd: '/repo', command: 'npm run build:prod' },
      result: 'Build completed in 42s',
      success: true,
      durationMs: 42000,
      timestamp: iso(1000 * 60 * 34),
    },
    {
      id: 'tc-e2',
      toolName: 'Bash',
      arguments: { cwd: '/repo', command: 'npm run test:integration' },
      result: '24 tests passed',
      success: true,
      durationMs: 8000,
      timestamp: iso(1000 * 60 * 33.5),
    },
    {
      id: 'tc-e3',
      toolName: 'Bash',
      arguments: { cwd: '/repo', command: 'npm run deploy:prod' },
      result: 'Error: STRIPE_API_KEY is not set',
      success: false,
      durationMs: 1200,
      timestamp: iso(1000 * 60 * 33),
    },
    {
      id: 'tc-e4',
      toolName: 'Read',
      arguments: { cwd: '/repo', path: '.env.production' },
      result: 'File not found',
      success: false,
      durationMs: 45,
      timestamp: iso(1000 * 60 * 32.5),
    },
  ],
  reflection: {
    verdict: 'abort_goal',
    confidence: 0.95,
    qualityScore: 0.0,
    reasoning: 'Cannot proceed without required secrets. User must configure STRIPE_API_KEY in environment.',
    issues: ['Missing STRIPE_API_KEY', 'No .env.production file found'],
  },
  llmCalls: [],
  planSnapshots: [],
  userPrompts: [],
  contextWindow: {
    contextTokens: 140000,
    outputTokens: 13400,
    totalTokens: 153400,
    maxTokens: 200000,
    percentageUsed: 0.70,
    messageCount: 32,
    timestamp: iso(1000 * 60 * 32),
  },
};

const queuedRequest: AgentRequest = {
  id: 'task-004',
  sessionId: 'S-1043',
  state: 'queued',
  userInput: 'Add unit tests for the user profile component',
  createdAt: iso(1000 * 60 * 2),
  stepsCompleted: 0,
  stepsTotal: 0,
  totalToolCalls: 0,
  toolCalls: [],
  llmCalls: [],
  planSnapshots: [],
  userPrompts: [],
};

// ============================================
// MOCK SESSIONS WITH REQUESTS
// ============================================

export const mockSessions: Session[] = [
  sess({
    id: 'S-1042',
    userId: 'user_81b2',
    state: 'active',
    env: 'prod',
    createdAt: iso(1000 * 60 * 40),
    startedAt: iso(1000 * 60 * 34),
    tags: ['voice', 'project-alpha'],
    meta: {
      clientType: 'voice',
      workingDir: '/home/dev/project-alpha',
    },
    legacyRequests: [],
    requests: [runningRequest, successRequest, errorRequest],
  }),
  sess({
    id: 'S-1043',
    userId: 'user_1f0a',
    state: 'idle',
    env: 'dev',
    createdAt: iso(1000 * 60 * 15),
    startedAt: iso(1000 * 60 * 12),
    tags: ['tui', 'sandbox'],
    meta: {
      clientType: 'tui',
      workingDir: '/home/dev/sandbox',
    },
    legacyRequests: [],
    requests: [queuedRequest],
  }),
  sess({
    id: 'S-1044',
    userId: 'user_3x7p',
    state: 'ended',
    env: 'staging',
    createdAt: iso(1000 * 60 * 60),
    startedAt: iso(1000 * 60 * 55),
    endedAt: iso(1000 * 60 * 45),
    tags: ['api', 'ci-pipeline'],
    meta: {
      clientType: 'api',
      workingDir: '/builds/ci-runner/workspace',
    },
    legacyRequests: [],
    requests: [
      {
        id: 'task-005',
        sessionId: 'S-1044',
        state: 'success',
        userInput: 'Run the full test suite and report coverage',
        createdAt: iso(1000 * 60 * 55),
        startedAt: iso(1000 * 60 * 54),
        endedAt: iso(1000 * 60 * 46),
        stepsCompleted: 3,
        stepsTotal: 3,
        totalToolCalls: 4,
        durationMs: 8 * 60 * 1000,
        plan: {
          goal: 'Execute full test suite with coverage',
          steps: [
            { stepNum: 1, objective: 'Install dependencies', status: 'completed', phase: 'execution', required: true, durationMs: 12000 },
            { stepNum: 2, objective: 'Run pytest with coverage', status: 'completed', phase: 'execution', toolHint: 'Bash', required: true, durationMs: 180000 },
            { stepNum: 3, objective: 'Generate coverage report', status: 'completed', phase: 'execution', required: true, durationMs: 5000 },
          ],
        },
        toolCalls: [
          { id: 'tc-ci1', toolName: 'Bash', arguments: { cwd: '/repo', command: 'pip install -e .[dev]' }, result: 'Installed 45 packages', success: true, durationMs: 11500, timestamp: iso(1000 * 60 * 54) },
          { id: 'tc-ci2', toolName: 'Bash', arguments: { cwd: '/repo', command: 'pytest --cov=src' }, result: '156 tests, 94% coverage', success: true, durationMs: 178000, timestamp: iso(1000 * 60 * 52) },
          { id: 'tc-ci3', toolName: 'Bash', arguments: { cwd: '/repo', command: 'coverage html' }, result: 'HTML report generated', success: true, durationMs: 4800, timestamp: iso(1000 * 60 * 47) },
          { id: 'tc-ci4', toolName: 'Read', arguments: { cwd: '/repo', path: 'coverage/index.html' }, result: '2.4KB', success: true, durationMs: 45, timestamp: iso(1000 * 60 * 46.5) },
        ],
        reflection: {
          verdict: 'accept',
          confidence: 0.98,
          qualityScore: 0.94,
          reasoning: 'All 156 tests passed. Coverage at 94% exceeds threshold. Report generated successfully.',
          issues: [],
        },
        llmCalls: [],
        planSnapshots: [],
        userPrompts: [],
      },
    ],
  }),
];
