/**
 * ID System for Agent Memory
 *
 * Provides globally unique, time-ordered, source-traceable identifiers
 * that support idempotent operations.
 *
 * Design decisions:
 * - ULID over UUIDv4/v7 for time-ordering and index locality
 * - Source refs include account_id to prevent cross-account collisions
 * - Two-tier deduplication: RawEnvelope and Canonical Entity levels
 */

import { monotonicFactory, decodeTime } from 'ulid'
import { z } from 'zod'
import { createHash } from 'crypto'
import { stableStringify } from './stable-stringify.js'

// Use monotonicFactory for strictly increasing IDs within the same millisecond
const ulid = monotonicFactory()

// ============ Connector Types ============

export const ConnectorTypeSchema = z.enum(['github', 'gmail', 'xcom', 'imessage', 'claude_sessions', 'rex_sessions'])
export type ConnectorType = z.infer<typeof ConnectorTypeSchema>

// ============ ID Types ============

/**
 * ULID format regex: 26 characters from Crockford's base32 alphabet
 * Example: 01ARZ3NDEKTSV4RRFFQ69G5FAV
 */
export const ULID_REGEX = /^[0-9A-HJKMNP-TV-Z]{26}$/

export const UlidSchema = z.string().regex(ULID_REGEX, 'Invalid ULID format')

/**
 * Canonical entity IDs - generated by our system using ULID format.
 * Time-ordered, lexicographically sortable, 128-bit compatible with UUID columns.
 */
export type CanonicalId = string

/**
 * Source IDs - opaque strings from external systems.
 * Format varies by connector (e.g., "123", "abc123def", "msg-uuid").
 */
export type SourceId = string

// ============ Source Reference ============

/**
 * Composite source reference that uniquely identifies an entity from an external system.
 * The combination of (connector, account_id, entity_type, source_id) is globally unique.
 */
export const SourceRefSchema = z.object({
  /** Connector type: which external system this entity came from */
  connector: ConnectorTypeSchema,
  /** External account identifier - scopes entities to prevent cross-account collisions */
  account_id: z.string().min(1),
  /** Entity type within the connector (e.g., 'issue', 'message', 'tweet') */
  entity_type: z.string().min(1),
  /** ID from the source system */
  source_id: z.string().min(1),
  /** Optional version for change detection (ETag, version number, or hash) */
  source_version: z.string().optional(),
})

export type SourceRef = z.infer<typeof SourceRefSchema>

// ============ ID Generation ============

/**
 * Generate a new canonical ID using ULID.
 * ULIDs are monotonically increasing within the same millisecond.
 */
export function generateCanonicalId(): CanonicalId {
  return ulid()
}

/**
 * Extract the timestamp from a ULID.
 * Returns the Unix timestamp in milliseconds.
 */
export function extractTimestamp(id: CanonicalId): number {
  return decodeTime(id)
}

/**
 * Validate that a string is a valid ULID.
 */
export function isValidUlid(id: string): boolean {
  return ULID_REGEX.test(id)
}

// ============ Source Reference Keys ============

/**
 * Generate a deterministic key from a source reference.
 * Used for entity deduplication and lookups.
 *
 * Format: connector:account_id:entity_type:source_id
 */
export function sourceRefToKey(ref: SourceRef): string {
  return `${ref.connector}:${ref.account_id}:${ref.entity_type}:${ref.source_id}`
}

/**
 * Parse a source ref key back into its components.
 * Returns null if the key format is invalid.
 */
export function parseSourceRefKey(key: string): Omit<SourceRef, 'source_version'> | null {
  const parts = key.split(':')
  if (parts.length < 4) return null

  const [connector, account_id, entity_type, ...source_id_parts] = parts
  const source_id = source_id_parts.join(':') // Handle source_ids that contain colons

  const result = ConnectorTypeSchema.safeParse(connector)
  if (!result.success) return null

  return {
    connector: result.data,
    account_id,
    entity_type,
    source_id,
  }
}

// ============ Idempotency Keys ============

/**
 * Idempotency keys for two-tier deduplication:
 * - raw_key: For RawEnvelope deduplication (includes raw data hash)
 * - entity_key: For canonical entity deduplication (source ref only)
 */
export interface IdempotencyKeys {
  /** For RawEnvelope dedup - includes raw data hash */
  raw_key: string
  /** For canonical entity dedup - source ref only */
  entity_key: string
}

/**
 * Compute SHA-256 hash of a string.
 */
export function sha256(data: string): string {
  return createHash('sha256').update(data).digest('hex')
}

/**
 * Compute idempotency keys for a source record.
 *
 * Two-tier deduplication strategy:
 * 1. RawEnvelope Dedup: Before storing raw data
 *    - Key: sha256(connector + account_id + source_id + raw_data_hash)
 *    - Permanent (raw data is append-only)
 *
 * 2. Canonical Entity Dedup: During normalization
 *    - Key: connector:account_id:entity_type:source_id
 *    - Behavior: Update existing canonical entity if source_ref exists
 */
export function computeIdempotencyKeys(
  connector: ConnectorType,
  accountId: string,
  entityType: string,
  sourceId: string,
  rawData: unknown
): IdempotencyKeys {
  const entityKey = `${connector}:${accountId}:${entityType}:${sourceId}`
  const rawHash = sha256(stableStringify(rawData))
  const rawKey = sha256(`${entityKey}:${rawHash}`)

  return {
    raw_key: rawKey,
    entity_key: entityKey,
  }
}

/**
 * Compute a hash for raw data to detect changes.
 * Uses stable stringify for deterministic hashing.
 */
export function computeRawDataHash(rawData: unknown): string {
  return sha256(stableStringify(rawData))
}

// ============ Batch ID Generation ============

/**
 * Pre-generate a batch of canonical IDs for bulk operations.
 * Useful for high-throughput ingestion where ID generation
 * performance is critical.
 */
export function generateCanonicalIdBatch(count: number): CanonicalId[] {
  const ids: CanonicalId[] = new Array(count)
  for (let i = 0; i < count; i++) {
    ids[i] = ulid()
  }
  return ids
}

// ============ ID Comparison ============

/**
 * Compare two ULIDs lexicographically.
 * Returns negative if a < b, positive if a > b, zero if equal.
 * Since ULIDs are time-ordered, this also orders by creation time.
 */
export function compareUlids(a: CanonicalId, b: CanonicalId): number {
  return a.localeCompare(b)
}

/**
 * Get the older of two ULIDs (the one created first).
 */
export function olderUlid(a: CanonicalId, b: CanonicalId): CanonicalId {
  return compareUlids(a, b) <= 0 ? a : b
}

/**
 * Get the newer of two ULIDs (the one created most recently).
 */
export function newerUlid(a: CanonicalId, b: CanonicalId): CanonicalId {
  return compareUlids(a, b) >= 0 ? a : b
}
